### ISSUE TITLE
Issue when enabling the "Hide Reddit Premium" option in "Hide Elements"

### ISSUE THREAD

**Issue by ThayerRodar** [joelacus/RedditEnhancer#11]
When I have "Hide Reddit Premium" enabled, my username and karma drop-down at the top right of the page disappear. This only happens with an account that currently has reddit premium. I have this element hidden on other accounts that don't currently have reddit premium and the drop-down menu is unaffected.

**Comment by joelacus** [comment]
Ah interesting, I think I know the issue. I'm guessing that the username dropdown menu contains the reddit premium icon if you have reddit premium? That's what my script looks for to find the premium banner, I just need to limit its search to just the sidebar instead of the whole page. What browser do you use? I can release the update for that first for you to try.

**Comment by ThayerRodar** [comment]
Yes, the dropdown has the premium icon. I use Firefox for Windows 10.

**Comment by joelacus** [comment]
Great! I have just published version 0.15.1 with a fix. You'll get the update automatically soon, or you can check for updates now on the "Manage extensions" page (about:addons). Refresh any open reddit tabs and let me know if it works :)

**Comment by ThayerRodar** [comment]
Works great now. Thanks!
