### ISSUE TITLE
[Feature Request] Always show the button "All" in the top bar

### ISSUE THREAD

**Issue by fabiotp91** [joelacus/RedditEnhancer#7]
Reddit in it's infinite knowledge decided to remove the "All" button from the top bar and now every time we want to see "r/all" we need to input it in the url or search in the subreddit search bar, because they left it in the bottom of it.

Is there a way to bring the "All" button back to the top bar for easy access ?

**Comment by joelacus** [comment]
Hi. I have just uploaded a new update (0.9.0) yesterday actually to add an 'r/All' button to the header :). Also an option to move the 'Feeds' section in the side menu to the top. (Chrome and Edge will take about a week to process my update).
In the last couple days though, it looks like reddit have removed the 'Happening Now' button from the header and the side menu. Maybe they discontinued that feature since https://www.reddit.com/now doesn't work for me now.

**Comment by fabiotp91** [comment]
Ohhh I can see it in Firefox! 
That's exactly what I was asking for!

Thanks a lot for all these extra features.

**Comment by joelacus** [comment]
You're welcome, and thank you very much for the donation! :D
