### ISSUE TITLE
Comments don't expand automatically for the Old UI

### ISSUE THREAD

**Issue by JSCFORCE** [joelacus/RedditEnhancer#71]
It works correctly when I use the New UI but is broken for the Old UI.

**Comment by joelacus** [comment]
Hi. That feature currently doesn't support old reddit, but I can work on it for the next version.

**Comment by JSCFORCE** [comment]
I see. Please do. I would greatly appreciate it. I use the Old UI exclusively. Thank you! :)

**Comment by joelacus** [comment]
I've just published version 1.10.1. The "Auto Load Hidden Comments" and "Auto Load More Comments/Replies" now support old reddit. I've also optimised these features as well so that they work as you scroll down the page, instead of trying to open all the comments at once, so this should help to reduce memory usage and lag. :)

**Comment by JSCFORCE** [comment]
You are the man!!! Thank you so much.
